# Generated by Django 3.0.2 on 2020-02-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
