# Generated by Django 3.0.2 on 2020-02-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_api', '0002_auto_20200215_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='access',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
